# Generated by Django 5.2.16 on 2026-07-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_backdrop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
