# Generated by Django 5.2.16 on 2026-08-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_cast_movie_director_movie_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='media_type',
            field=models.CharField(default='movie', max_length=20),
        ),
    ]
